[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "cd backend && npm install",
  "cd ../seat-reservation-frontend && npm install"
]

[phases.build]
cmds = [
  "cd seat-reservation-frontend && npm run build"
]

[phases.start]
cmds = [
  "cd backend && npm start"
]
